"""Core Brain implementation.

Phase 1 provides the deterministic Memory Engine, Phase 2 the ingestion
pipeline, Phase 3 the LLM Gateway + Understanding, Phase 4 the Context Engine +
semantic search abstraction, Phase 5 People Intelligence (people, relationships,
preferences). No embeddings yet; lexical search is the deterministic MVP.
"""

from .context import (
    Context,
    ContextEngine,
    ContextLimits,
    ContextStatus,
    ContextValidationError,
    LexicalSemanticSearch,
    RankConfig,
    Ranker,
    ScoredMemory,
    SearchMetadata,
    SearchQuery,
    SemanticSearch,
)
from .ingestion import (
    DeterministicEventProcessor,
    EventProcessingError,
    EventProcessor,
    EventReceiptRepository,
    EventValidationError,
    IngestionError,
    IngestionOutcome,
    IngestionReceipt,
    IngestionResult,
    IngestionService,
    MappingRule,
    ReceiptStorageError,
    SqliteEventReceiptRepository,
    build_ingestion,
)
from .memory import (
    MemoryCandidate,
    MemoryClassifier,
    MemoryEngineError,
    MemoryNotFoundError,
    MemoryQuery,
    MemoryRepository,
    MemoryService,
    MemoryStatusFilter,
    MemoryValidationError,
    SqliteMemoryRepository,
    TemporalValidityError,
)
from .people import (
    DeveloperPreferences,
    PeopleIntelligence,
    PeopleLimits,
    PeopleSummary,
    PersonProfile,
    Preference,
    PreferenceDomain,
)
from .understanding import (
    DeveloperAnalysis,
    DeveloperContext,
    GatewayConfig,
    InvalidLLMOutputError,
    LLMGateway,
    LLMGatewayError,
    LLMProvider,
    LLMProviderError,
    LLMTimeoutError,
    UnderstandingError,
    UnderstandingIntent,
    UnderstandingResult,
    build_gateway,
)

__all__ = [
    "Context",
    "ContextEngine",
    "ContextLimits",
    "ContextStatus",
    "ContextValidationError",
    "DeveloperAnalysis",
    "DeveloperContext",
    "DeveloperPreferences",
    "DeterministicEventProcessor",
    "EventProcessingError",
    "EventProcessor",
    "EventReceiptRepository",
    "EventValidationError",
    "GatewayConfig",
    "IngestionError",
    "IngestionOutcome",
    "IngestionReceipt",
    "IngestionResult",
    "IngestionService",
    "InvalidLLMOutputError",
    "LexicalSemanticSearch",
    "LLMGateway",
    "LLMGatewayError",
    "LLMProvider",
    "LLMProviderError",
    "LLMTimeoutError",
    "MappingRule",
    "MemoryCandidate",
    "MemoryClassifier",
    "MemoryEngineError",
    "MemoryNotFoundError",
    "MemoryQuery",
    "MemoryRepository",
    "MemoryService",
    "MemoryStatusFilter",
    "MemoryValidationError",
    "PeopleIntelligence",
    "PeopleLimits",
    "PeopleSummary",
    "PersonProfile",
    "Preference",
    "PreferenceDomain",
    "RankConfig",
    "Ranker",
    "ReceiptStorageError",
    "ScoredMemory",
    "SearchMetadata",
    "SearchQuery",
    "SemanticSearch",
    "SqliteEventReceiptRepository",
    "SqliteMemoryRepository",
    "TemporalValidityError",
    "UnderstandingError",
    "UnderstandingIntent",
    "UnderstandingResult",
    "build_gateway",
    "build_ingestion",
]