"""Core Brain implementation.

Phase 1 provides the deterministic Memory Engine, Phase 2 the ingestion
pipeline, Phase 3 the LLM Gateway + Understanding. No embeddings or semantic
search yet.
"""

from .ingestion import (
    DeterministicEventProcessor,
    EventProcessingError,
    EventProcessor,
    EventReceiptRepository,
    EventValidationError,
    IngestionError,
    IngestionOutcome,
    IngestionReceipt,
    IngestionResult,
    IngestionService,
    MappingRule,
    ReceiptStorageError,
    SqliteEventReceiptRepository,
    build_ingestion,
)
from .memory import (
    MemoryCandidate,
    MemoryClassifier,
    MemoryEngineError,
    MemoryNotFoundError,
    MemoryQuery,
    MemoryRepository,
    MemoryService,
    MemoryStatusFilter,
    MemoryValidationError,
    SqliteMemoryRepository,
    TemporalValidityError,
)
from .understanding import (
    DeveloperAnalysis,
    DeveloperContext,
    GatewayConfig,
    InvalidLLMOutputError,
    LLMGateway,
    LLMGatewayError,
    LLMProvider,
    LLMProviderError,
    LLMTimeoutError,
    UnderstandingError,
    UnderstandingIntent,
    UnderstandingResult,
    build_gateway,
)

__all__ = [
    "DeveloperAnalysis",
    "DeveloperContext",
    "DeterministicEventProcessor",
    "EventProcessingError",
    "EventProcessor",
    "EventReceiptRepository",
    "EventValidationError",
    "GatewayConfig",
    "IngestionError",
    "IngestionOutcome",
    "IngestionReceipt",
    "IngestionResult",
    "IngestionService",
    "InvalidLLMOutputError",
    "LLMGateway",
    "LLMGatewayError",
    "LLMProvider",
    "LLMProviderError",
    "LLMTimeoutError",
    "MappingRule",
    "MemoryCandidate",
    "MemoryClassifier",
    "MemoryEngineError",
    "MemoryNotFoundError",
    "MemoryQuery",
    "MemoryRepository",
    "MemoryService",
    "MemoryStatusFilter",
    "MemoryValidationError",
    "ReceiptStorageError",
    "SqliteEventReceiptRepository",
    "SqliteMemoryRepository",
    "TemporalValidityError",
    "UnderstandingError",
    "UnderstandingIntent",
    "UnderstandingResult",
    "build_gateway",
    "build_ingestion",
]