export const POSITIONS = {
  corner: [-3.2, 1.4, -2.0],
  corner_low: [-3.2, 0.5, -2.0],
  center: [0.0, 0.0, 0.0],
  center_left: [-0.9, 0.3, 0.0],
  center_upper: [0.0, 1.0, 0.0],
  bottom_center: [0.0, -1.6, 0.0],
  attention_area: [0.0, 0.3, 1.6],
};

export const STATE_SPEC = {
  IDLE: {
    animation: "hover",
    movement: "none",
    speed: 0.1,
    position: "corner",
    scale: 1.0,
    visibility: "dim",
    duration_ms: 0,
    priority: 0,
  },
  BACKGROUND: {
    animation: "drift",
    movement: "slow",
    speed: 0.2,
    position: "corner",
    scale: 0.8,
    visibility: "low",
    duration_ms: 3000,
    priority: 1,
  },
  ATTENTION: {
    animation: "perk",
    movement: "toward_center",
    speed: 0.5,
    position: "center_left",
    scale: 1.2,
    visibility: "normal",
    duration_ms: 2500,
    priority: 2,
  },
  CURIOUS: {
    animation: "tilt",
    movement: "circle",
    speed: 0.4,
    position: "center",
    scale: 1.1,
    visibility: "normal",
    duration_ms: 3000,
    priority: 3,
  },
  LISTENING: {
    animation: "hover_tilt",
    movement: "subtle",
    speed: 0.3,
    position: "bottom_center",
    scale: 1.1,
    visibility: "normal",
    duration_ms: 4000,
    priority: 3,
  },
  THINKING: {
    animation: "stutter",
    movement: "minimal",
    speed: 0.2,
    position: "center",
    scale: 1.0,
    visibility: "normal",
    duration_ms: 4000,
    priority: 4,
  },
  PROCESSING: {
    animation: "spin",
    movement: "orbiting",
    speed: 0.6,
    position: "center",
    scale: 1.0,
    visibility: "normal",
    duration_ms: 3500,
    priority: 5,
  },
  LEARNING: {
    animation: "pulse",
    movement: "slow_orbit",
    speed: 0.5,
    position: "center_upper",
    scale: 1.2,
    visibility: "bright",
    duration_ms: 5000,
    priority: 6,
  },
  IMPORTANT: {
    animation: "zoom_alert",
    movement: "toward_user",
    speed: 0.9,
    position: "attention_area",
    scale: 1.5,
    visibility: "bright",
    duration_ms: 8000,
    priority: 7,
    requires_ack: true,
  },
  WAITING: {
    animation: "pacing",
    movement: "sway",
    speed: 0.3,
    position: "bottom_center",
    scale: 1.0,
    visibility: "normal",
    duration_ms: 0,
    priority: 6,
  },
  SUCCESS: {
    animation: "happy_bounce",
    movement: "bounce",
    speed: 0.7,
    position: "center",
    scale: 1.2,
    visibility: "bright",
    duration_ms: 2500,
    priority: 7,
  },
  WARNING: {
    animation: "shake",
    movement: "agitated",
    speed: 1.2,
    position: "attention_area",
    scale: 1.3,
    visibility: "bright",
    duration_ms: 5000,
    priority: 8,
  },
  ERROR: {
    animation: "falter",
    movement: "stumble",
    speed: 0.8,
    position: "center",
    scale: 1.0,
    visibility: "normal",
    duration_ms: 4000,
    priority: 9,
  },
  SLEEPING: {
    animation: "slow_pulse",
    movement: "landed",
    speed: 0.05,
    position: "corner_low",
    scale: 0.7,
    visibility: "dim",
    duration_ms: 0,
    priority: -1,
  },
};

export function resolve(state) {
  return STATE_SPEC[state] ?? { ...STATE_SPEC.IDLE, fallback: true };
}

export function positionOf(position) {
  return POSITIONS[position] ?? POSITIONS.corner;
}

export function defaultDispatcherTimeMs(spec) {
  return spec.duration_ms > 0 ? spec.duration_ms : 0;
}